### ISSUE TITLE
Google reCaptcha v2

### ISSUE THREAD

**Issue by joesixpack** [ava-labs/avalanche-faucet-legacy#1]
Does not recognize "localhost" as a domain, but does local IP.

**Comment by collincusce** [comment]
Please elaborate. Google reCaptcha v2 works fine with "localhost". If you're having problems with Google's website, report a bug to Google.

**Comment by joesixpack** [comment]
In my case, the reCaptcha just wouldn't come up and work using localhost instead of the actual IP of the machine.  Had to put in the IP at Google.
