### ISSUE TITLE
Minor bug. Faucet Balance shows 0

### ISSUE THREAD

**Issue by derfredy** [ava-labs/avalanche-faucet-legacy#3]
This is a minor bug and not breaking anything. When you start the faucet in production mode it says it has no balance. In fact it really has.

![image](https://user-images.githubusercontent.com/23276270/79110497-d74f4500-7d7a-11ea-94fe-c3430da3cacc.png)

If you query the balance you get the real amount:
{
  "jsonrpc": "2.0",
  "result": {
    "balance": "45000000000000000"
  },
  "id": 2
}

**Comment by kanatliemre** [comment]
This issue should be solved with the latest C-Chain updates.
