### ISSUE TITLE
Timeout of 1000ms exceeded 

### ISSUE THREAD

**Issue by glefait** [ava-labs/avalanche-faucet-legacy#7]
On the official faucet website, after google recaptcha validation, when clicking on "Request ...", I got the following JS error :

```createError.js:16 Uncaught (in promise) Error: timeout of 1000ms exceeded
    at t.exports (createError.js:16)
    at XMLHttpRequest.l.ontimeout (xhr.js:95)```

Tried both on mobile, wifi and wired connexion.

**Comment by kanatliemre** [comment]
This had to do with the network problems we had last week causing connection issues. But the front end should handle this error accordingly.
